Array Operations

In [1]:
import numpy as np

Arithmetic Operations

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [5]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [6]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [7]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1 // a2

array([0, 0, 0, 0, 0])

In [9]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [11]:
l = [10,20,30,40]
arr = np.array(l)

In [33]:
arr + 10

array([20, 30, 40, 50])

In [15]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
arr2 + 10   #This is classic example of broadcasting in martices not in vector

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

Deep and Shallow copy

In [18]:
a = np.arange(1,21)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [24]:
slice + 10


array([11, 12, 13, 14, 15])

In [26]:
slice = slice * 10
slice

array([100, 200, 300, 400, 500])

This is my own doubt clearence of shallow copy vs deep copy 

In [ ]:
lst = [1,2,3,4,5,6] #Ignore
lst

[1, 2, 3, 4, 5, 6]

In [ ]:
sliced = lst[:4] #Ignore
sliced

[1, 2, 3, 4]

In [ ]:
lst #ignore

[1, 2, 3, 4, 5, 6]

Matrix Operations

Advance Array Manipulation

Stacking Array

Splitting array