<a href="https://colab.research.google.com/github/polymathicneo/ML-Foundations/blob/main/numpybasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY BASICS - NEO SEDAI**

In [4]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [6]:
a = [1, 2, 3, 4]
a

[1, 2, 3, 4]

In [7]:
np.array(a)

array([1, 2, 3, 4])

In [8]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [13]:
arr = np.ones((6, 6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
arr = np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

**Random** Number Generation

This is the concept of normalization. the values is inbetween 0 and 1

In [15]:
np.random.rand(5)

array([0.3336965 , 0.26477363, 0.7250713 , 0.47340764, 0.53085488])

This is the concept of standardization. The values is inbetween 3 to -3

In [16]:
np.random.randn(10)

array([-1.84072299,  1.45657771,  1.04961209, -1.39446395,  2.20899874,
       -2.79380365, -1.18620522, -0.27288232,  0.66275648,  0.58012329])

In [17]:
np.random.randint(6)

0

In [18]:
np.random.randint(1, 10, 10)

array([7, 8, 9, 1, 5, 8, 1, 4, 1, 1], dtype=int32)

In [19]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr.shape

(3, 3)

In [21]:
arr.size

9

In [22]:
arr.dtype

dtype('int64')

# **Array Methods**

In [23]:
arr.min()

np.int64(1)

In [24]:
arr.max()

np.int64(9)

In [25]:
arr.sum()

np.int64(45)

In [26]:
np.sum(arr, axis = 0)  #This sums the vertical line

array([12, 15, 18])

In [27]:
np.sum(arr, axis = 1 ) #This sums the horizontal line

array([ 6, 15, 24])

In [28]:
arr.argmax()

np.int64(8)

In [29]:
arr.argmin()

np.int64(0)

# Reshaping and Resizing

In [30]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [33]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [36]:
arr[:, 3]

array([ 4,  9, 14, 19, 24, 29])

Boolean INDEXING

In [37]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [42]:
bool_index = arr % 2 ==0
bool_index

array([ True,  True,  True,  True,  True])

In [43]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])