Vector slicing

In [1]:
import numpy as np

In [4]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
arr[9]

np.int64(20)

In [10]:
arr[0:5]

array([11, 12, 13, 14, 15])

In [11]:
arr[:5]

array([11, 12, 13, 14, 15])

In [12]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [15]:
arr_slice = arr[0::2]
arr_slice

array([11, 13, 15, 17, 19])

In [17]:
arr1 = np.arange(1,31).reshape(6,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [18]:
arr1[0]

array([1, 2, 3, 4, 5])

In [19]:
arr1[0,0]

np.int64(1)

In [21]:
arr1[5,4]

np.int64(30)

In [24]:
slice1 = arr1[0:2, 1:3]
slice1

array([[2, 3],
       [7, 8]])

Numpy Indexing and slicing of Matrix

Boolean Indexing