<a href="https://colab.research.google.com/github/polymathicneo/ML-Foundations/blob/main/numpybasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY BASICS - NEO SEDAI**

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [ ]:
a = [1, 2, 3, 4]
a

[1, 2, 3, 4]

In [ ]:
np.array(a)

array([1, 2, 3, 4])

In [ ]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [ ]:
arr = np.ones((6, 6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
arr = np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

**Random** Number Generation

This is the concept of normalization. the values is inbetween 0 and 1

In [ ]:
np.random.rand(5)

array([0.70476355, 0.09691471, 0.98101475, 0.27515951, 0.85045472])

This is the concept of standardization. The values is inbetween 3 to -3

In [ ]:
np.random.randn(10)

array([-0.32059298,  2.62831015, -0.19440027, -0.46253354,  0.73022687,
        0.99281468, -0.75579608,  0.8125788 ,  0.59876256,  0.75865518])

In [ ]:
np.random.randint(6)

0

In [ ]:
np.random.randint(1, 10, 10)

array([7, 6, 2, 2, 8, 8, 9, 4, 9, 2])

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

# **Array Methods**

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr, axis = 0)  #This sums the vertical line

array([12, 15, 18])

In [ ]:
np.sum(arr, axis = 1 ) #This sums the horizontal line

array([ 6, 15, 24])

In [ ]:
arr.argmax()

np.int64(8)

In [ ]:
arr.argmin()

np.int64(0)

# Reshaping and Resizing

In [ ]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])